# Generated by Django 2.1.5 on 2020-09-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('S', 'SHIPPING_ADDRESS'), ('B', 'BILLING_ADDRESS')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SW', 'SPORTWEAR'), ('S', 'SHIRT'), ('OW', 'OUTWEAR')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='name_of_seller',
            field=models.CharField(choices=[('B', 'Bijas'), ('A', 'Ahammedunny')], max_length=1),
        ),
    ]
