# Generated by Django 2.1.5 on 2020-09-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20200912_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='biriyani',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('B', 'BILLING_ADDRESS'), ('S', 'SHIPPING_ADDRESS')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='labels',
            field=models.CharField(choices=[('D', 'danger'), ('S', 'secondary'), ('P', 'primary')], max_length=1),
        ),
    ]
